name: Build QuickNote APK with P4A

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git \
          zip \
          unzip \
          openjdk-11-jdk \
          autoconf \
          libtool \
          pkg-config \
          zlib1g-dev \
          libncurses5-dev

    - name: Install Android SDK and Accept Licenses
      uses: android-actions/setup-android@v2
      with:
        licenses: yes

    - name: Install Python-for-Android
      run: |
        pip install cython
        git clone https://github.com/kivy/python-for-android
        cd python-for-android
        pip install .

    - name: Build APK with P4A
      run: |
        cd app
        # Create a distribution and build the APK
        p4a create \
          --dist_name=quicknote \
          --bootstrap=sdl2 \
          --requirements=python3,kivy==2.2.1,kivymd==1.2.0,openssl,pyopenssl \
          --arch=arm64-v8a \
          --android-api=31 \
          --private . \
          --package=org.bigdev.quicknote \
          --name="QuickNote" \
          --version=1.0 \
          --orientation=portrait \
          --permission=WRITE_EXTERNAL_STORAGE \
          --permission=READ_EXTERNAL_STORAGE

        # The APK will be in the quicknote/dist/ directory
        ls -la quicknote/dist/

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: QuickNote-APK
        path: app/quicknote/dist/*.apk
