name: Build QuickNote APK

on:
  push:
    branches: [ main ]
  workflow_dispatch: # This allows you to manually trigger the build from the GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Android APK
      run: |
        # Install system dependencies
        apt-get update
        apt-get install -y git zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev libncurses5-dev libtinfo5 libstdc++-12-dev

        # Install Buildozer and Cython
        pip install --upgrade pip wheel setuptools virtualenv
        pip install buildozer Cython==0.29.33

        # Navigate to the app directory and run buildozer
        cd app
        buildozer android debug

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v3
      with:
        name: QuickNote-APK
        path: app/bin/*.apk
