name: Build QuickNote APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install System Dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y \
          git \
          zip \
          unzip \
          openjdk-11-jdk \
          autoconf \
          libtool \
          pkg-config \
          zlib1g-dev \
          libncurses5-dev \
          libtinfo5 \
          libstdc++6

    - name: Install Python Build Dependencies
      run: |
        python -m pip install --upgrade pip wheel setuptools virtualenv
        pip install buildozer Cython==0.29.33

    - name: Build APK with Buildozer
      run: |
        cd app
        
        # Set Android SDK root environment variable
        export ANDROID_HOME=/usr/local/lib/android/sdk
        
        # Accept all Android SDK licenses with correct path
        yes | ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --licenses || true
        
        # Now run buildozer with the rock-solid versions
        buildozer android debug

    - name: Upload APK Artifact
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: QuickNote-APK
        path: app/bin/*.apk
